tasks:
- id: 741ae11a
  name: test-notif
  schedule: 0 0 * * *
  working_dir: /home/dontizi/Projects/codegueass
  skill: null
  prompt: Say hello world
  allowed_tools: []
  model: sonnet
  autonomous: false
  max_turns: null
  timeout: 300
  enabled: true
  variables: {}
  last_run: '2026-01-29T03:16:47.198991'
  last_status: success
  notifications:
    channels:
    - edcc20a4
    events:
    - task_start
    - task_success
    - task_failure
    include_output: true
- id: 8b2c9f3d
  name: ClawdBot Review
  schedule: 0 9 * * *
  working_dir: /home/dontizi/Projects/codegueass
  skill: trend-research
  prompt: AI
  allowed_tools: []
  model: sonnet
  autonomous: false
  max_turns: null
  timeout: 300
  enabled: true
  variables: {}
  last_run: '2026-01-29T03:15:55.474854'
  last_status: success
  notifications:
    channels:
    - edcc20a4
    events:
    - task_failure
    - task_start
    - task_success
    include_output: true
